name: maven project in self hosted
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: cloning maven
        uses: actions/checkout@v7.0.0
      - name: checking version
        shell: cmd
        run: java --version
      - name: checking maven version
        shell: cmd
        run: mvn --version
      - name: generating package
        shell: cmd
        run: mvn package
